spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_system
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
